remote_theme: riggraz/no-style-please
title: "taylor's notes"
author: Taylor Robinson
email: tayyiorrobinson@gmail.com
url: https://robins.one # root address of the site
baseurl: "/notes" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Taylor's notes about things, stuff and et cetera. 

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)

plugins:
  - jekyll-feed

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%d/%m/%Y" # customize how date is formatted
  show_description: false # show blog description in home page

